### ISSUE TITLE
json problem

### ISSUE THREAD

**Issue by gurkanboll** [wozhub/lime-py-api#1]
are you still working on this project @dvinazza david? cant seem the get the reproducible example for limesurveys online demo to work, nor my own domain for ls aswell. 

<p>Error: <type 'exceptions.ValueError'></p>

Traceback (most recent call last):
  File "ejemplo.py", line 11, in <module>
    lime = Api(url, usuario, clave)
  File "/Users/path/limesurvey.py", line 22, in **init**
    self.session_key = self._obtenerJson(data)['result']
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by wozhub** [comment]
Hello Gurkanboll. I'm not using this anymore, yet it was working last time I checked. I believe it was limesurvey 2.01+ or 2.03. They might have made some major changes in the API but the API being buggy was the reason I started this glue...

**Comment by gurkanboll** [comment]
Ah, okey, well, haven't seen any major changes, but yet again im pretty new to python and json. trying it on 2.05+ and 2.06 build

**Comment by gurkanboll** [comment]
Installing json-rpc did the trick
